# This file was generated by GoReleaser. DO NOT EDIT.
cask "scorebug" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "cccbfb9dd6f78a6b4cce5058d1f818a921279349a0def341df63e357386c1e2b"
      url "https://github.com/KevinStirling/scorebug.sh/releases/download/v#{version}/scorebug.sh_Darwin_x86_64.tar.gz",
        verified: "github.com/KevinStirling/scorebug.sh"
    end
    on_arm do
      sha256 "aff00682892bb941e71b6b1cadc3158fecb13a709f1eb229e24c58084030c695"
      url "https://github.com/KevinStirling/scorebug.sh/releases/download/v#{version}/scorebug.sh_Darwin_arm64.tar.gz",
        verified: "github.com/KevinStirling/scorebug.sh"
    end
  end

  on_linux do
    on_intel do
      sha256 "bfca3886c9fd58425179aa6262ba4e8bb74542d5daa23939e2fd387b862701dd"
      url "https://github.com/KevinStirling/scorebug.sh/releases/download/v#{version}/scorebug.sh_Linux_x86_64.tar.gz",
        verified: "github.com/KevinStirling/scorebug.sh"
    end
    on_arm do
      sha256 "bef2c6ae83d06ac6c0745a5f231e05425e158729ff2513120d1d3b26b9af8fd6"
      url "https://github.com/KevinStirling/scorebug.sh/releases/download/v#{version}/scorebug.sh_Linux_arm64.tar.gz",
        verified: "github.com/KevinStirling/scorebug.sh"
    end
  end

  name "scorebug"
  desc "Live MLB scores in your terminal"
  homepage "https://github.com/KevinStirling/scorebug.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scorebug"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scorebug"]
    end
  end

  # No zap stanza required

end
