# This file was generated by GoReleaser. DO NOT EDIT.
cask "scorebug" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "2777021fb91ca24305dcee1eac706473ec0e99aa89d36234904d032fb7de2036"
      url "https://github.com/KevinStirling/scorebug.sh/releases/download/v#{version}/scorebug.sh_Darwin_x86_64.tar.gz",
        verified: "github.com/KevinStirling/scorebug.sh"
    end
    on_arm do
      sha256 "76db6a28a7ce8fa1d4f2aba5a1b924b37d11eb3a2ece6a7b4112b9351d11c28c"
      url "https://github.com/KevinStirling/scorebug.sh/releases/download/v#{version}/scorebug.sh_Darwin_arm64.tar.gz",
        verified: "github.com/KevinStirling/scorebug.sh"
    end
  end

  on_linux do
    on_intel do
      sha256 "fe64ac5341ba10e71f68998eb52dc2441bc6c5436f265e95cacd34c3385f4a3d"
      url "https://github.com/KevinStirling/scorebug.sh/releases/download/v#{version}/scorebug.sh_Linux_x86_64.tar.gz",
        verified: "github.com/KevinStirling/scorebug.sh"
    end
    on_arm do
      sha256 "f2aa884770ba95354122037fcc5371dbdbea7efe42a9b8bf26845626e52c2f76"
      url "https://github.com/KevinStirling/scorebug.sh/releases/download/v#{version}/scorebug.sh_Linux_arm64.tar.gz",
        verified: "github.com/KevinStirling/scorebug.sh"
    end
  end

  name "scorebug"
  desc "Live MLB scores in your terminal"
  homepage "https://github.com/KevinStirling/scorebug.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scorebug"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scorebug"]
    end
  end

  # No zap stanza required

end
