# This file was generated by GoReleaser. DO NOT EDIT.
cask "scorebug" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "47268250d4aded89b7baed1b066e5f87eb89d1296e74b2b5a688305f13fa9b55"
      url "https://github.com/KevinStirling/scorebug.sh/releases/download/v#{version}/scorebug.sh_Darwin_x86_64.tar.gz",
        verified: "github.com/KevinStirling/scorebug.sh"
    end
    on_arm do
      sha256 "a0d8faf2ca5d603c161c564a324ee758b1a9c1578ed40f132e6361295dd952ac"
      url "https://github.com/KevinStirling/scorebug.sh/releases/download/v#{version}/scorebug.sh_Darwin_arm64.tar.gz",
        verified: "github.com/KevinStirling/scorebug.sh"
    end
  end

  on_linux do
    on_intel do
      sha256 "61ffb410d0e5b0f726f0986f0f97f2a754cc8169a6f29f6e859d9e4b689b6eba"
      url "https://github.com/KevinStirling/scorebug.sh/releases/download/v#{version}/scorebug.sh_Linux_x86_64.tar.gz",
        verified: "github.com/KevinStirling/scorebug.sh"
    end
    on_arm do
      sha256 "455d9727a9737b4c6708b6d6e98282646cd8c4626e1b0df52d2578bb1892374e"
      url "https://github.com/KevinStirling/scorebug.sh/releases/download/v#{version}/scorebug.sh_Linux_arm64.tar.gz",
        verified: "github.com/KevinStirling/scorebug.sh"
    end
  end

  name "scorebug"
  desc "Live MLB scores in your terminal"
  homepage "https://github.com/KevinStirling/scorebug.sh"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "scorebug"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/scorebug"]
    end
  end

  # No zap stanza required

end
